apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carbonverify-ingress
  namespace: carbonverify-staging
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/limit-rps: "4"
    nginx.ingress.kubernetes.io/limit-rpm: "200"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging-api.carbonverify.io
        - staging-app.carbonverify.io
      secretName: carbonverify-staging-tls
  rules:
    - host: staging-api.carbonverify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carbonverify-app
                port:
                  number: 8000
    - host: staging-app.carbonverify.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carbonverify-frontend
                port:
                  number: 80
