apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carbonverify-staging

namePrefix: staging-

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: carbonverify-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      kind: Deployment
      name: carbonverify-celery-worker
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: carbonverify-app-hpa
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target:
      kind: HorizontalPodAutoscaler
      name: carbonverify-celery-worker-hpa
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

images:
  - name: <ECR_REGISTRY>/carbonverify-app
    newTag: staging-latest
