"""add_email_hash_to_users

Revision ID: 271490077edf
Revises: c8e8775f56b9
Create Date: 2026-05-26 04:08:31.145303+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271490077edf'
down_revision: Union[str, None] = 'c8e8775f56b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = :t AND column_name = :c"
        ),
        {"t": table_name, "c": column_name},
    )
    return result.scalar() is not None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # These audit_logs indexes are already created by c8e8775f56b9 on the other branch;
    # use IF NOT EXISTS to avoid DuplicateTable errors when both branches are applied.
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_audit_logs_action_type ON audit_logs (action_type)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_id ON audit_logs (actor_id)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_audit_logs_timestamp ON audit_logs (timestamp)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_human_review_queue_assigned_to ON human_review_queue (assigned_to)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_human_review_queue_status ON human_review_queue (status)"))

    # email_hash column may have been added manually in prior backfill workflows;
    # ensure it exists before making it non-nullable / unique.
    if not _column_exists('users', 'email_hash'):
        op.add_column('users', sa.Column('email_hash', sa.String(length=64), nullable=True))
    op.alter_column('users', 'email_hash', nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('ix_users_email_hash', 'users', ['email_hash'], unique=False)
    op.create_unique_constraint('uq_users_email_hash', 'users', ['email_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email_hash', 'users', type_='unique')
    op.drop_index('ix_users_email_hash', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'email_hash')
    op.drop_index('ix_human_review_queue_status', table_name='human_review_queue')
    op.drop_index('ix_human_review_queue_assigned_to', table_name='human_review_queue')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_type', table_name='audit_logs')
    # ### end Alembic commands ###
