"""add_email_hash_to_users

Revision ID: 271490077edf
Revises: c8e8775f56b9
Create Date: 2026-05-26 04:08:31.145303+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271490077edf'
down_revision: Union[str, None] = 'c8e8775f56b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_action_type', 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_human_review_queue_assigned_to', 'human_review_queue', ['assigned_to'], unique=False)
    op.create_index('ix_human_review_queue_status', 'human_review_queue', ['status'], unique=False)

    # email_hash column was added manually and backfilled before running this migration
    op.alter_column('users', 'email_hash', nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('ix_users_email_hash', 'users', ['email_hash'], unique=False)
    op.create_unique_constraint('uq_users_email_hash', 'users', ['email_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email_hash', 'users', type_='unique')
    op.drop_index('ix_users_email_hash', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'email_hash')
    op.drop_index('ix_human_review_queue_status', table_name='human_review_queue')
    op.drop_index('ix_human_review_queue_assigned_to', table_name='human_review_queue')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_type', table_name='audit_logs')
    # ### end Alembic commands ###
