"""add_password_reset_required_to_users

Revision ID: 28b30d827f8d
Revises: d438fdf6cbab
Create Date: 2026-06-01 08:14:52.724859+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b30d827f8d'
down_revision: Union[str, None] = 'd438fdf6cbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_required')
    # ### end Alembic commands ###
