"""add version_id, unique active invite index, db cascade deletes

Revision ID: 6c85fff8b4b6
Revises: 28b30d827f8d
Create Date: 2026-06-01 09:00:00.139996+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c85fff8b4b6'
down_revision: Union[str, None] = '28b30d827f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_runs_project_id_fkey'), 'agent_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('brokerage_listings_project_id_fkey'), 'brokerage_listings', type_='foreignkey')
    op.create_foreign_key(None, 'brokerage_listings', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('calculation_runs', sa.Column('version_id', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('calculation_runs_project_id_fkey'), 'calculation_runs', type_='foreignkey')
    op.drop_constraint(op.f('calculation_runs_approved_by_fkey'), 'calculation_runs', type_='foreignkey')
    op.create_foreign_key(None, 'calculation_runs', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calculation_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carbon_credit_tokens_project_id_fkey'), 'carbon_credit_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'carbon_credit_tokens', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conflicts_of_interest_project_id_fkey'), 'conflicts_of_interest', type_='foreignkey')
    op.create_foreign_key(None, 'conflicts_of_interest', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('data_sources_project_id_fkey'), 'data_sources', type_='foreignkey')
    op.create_foreign_key(None, 'data_sources', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('enumerators_project_id_fkey'), 'enumerators', type_='foreignkey')
    op.create_foreign_key(None, 'enumerators', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('file_uploads_project_id_fkey'), 'file_uploads', type_='foreignkey')
    op.create_foreign_key(None, 'file_uploads', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('human_review_queue', sa.Column('version_id', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_human_review_queue_item', 'human_review_queue', ['item_type', 'item_id'], unique=False)
    op.drop_constraint(op.f('orchestrator_events_project_id_fkey'), 'orchestrator_events', type_='foreignkey')
    op.create_foreign_key(None, 'orchestrator_events', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('version_id', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('projects_developer_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    op.add_column('reports', sa.Column('version_id', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('reports_calculation_run_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_project_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'calculation_runs', ['calculation_run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('support_tickets_project_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('survey_responses_project_id_fkey'), 'survey_responses', type_='foreignkey')
    op.create_foreign_key(None, 'survey_responses', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_invites_active_email', 'user_invites', ['email_hash'], unique=True, postgresql_where=sa.text('used_at IS NULL'))
    op.add_column('validation_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.drop_constraint(op.f('whatsapp_conversations_project_id_fkey'), 'whatsapp_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'whatsapp_conversations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('whatsapp_conversations_project_id_fkey'), 'whatsapp_conversations', 'projects', ['project_id'], ['id'])
    op.drop_column('validation_runs', 'updated_at')
    op.drop_index('ix_user_invites_active_email', table_name='user_invites', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_constraint(None, 'survey_responses', type_='foreignkey')
    op.create_foreign_key(op.f('survey_responses_project_id_fkey'), 'survey_responses', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_project_id_fkey'), 'support_tickets', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_project_id_fkey'), 'reports', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('reports_calculation_run_id_fkey'), 'reports', 'calculation_runs', ['calculation_run_id'], ['id'])
    op.drop_column('reports', 'version_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_developer_id_fkey'), 'projects', 'developers', ['developer_id'], ['id'])
    op.drop_column('projects', 'version_id')
    op.drop_constraint(None, 'orchestrator_events', type_='foreignkey')
    op.create_foreign_key(op.f('orchestrator_events_project_id_fkey'), 'orchestrator_events', 'projects', ['project_id'], ['id'])
    op.drop_index('ix_human_review_queue_item', table_name='human_review_queue')
    op.drop_column('human_review_queue', 'version_id')
    op.drop_constraint(None, 'file_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('file_uploads_project_id_fkey'), 'file_uploads', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'enumerators', type_='foreignkey')
    op.create_foreign_key(op.f('enumerators_project_id_fkey'), 'enumerators', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.create_foreign_key(op.f('data_sources_project_id_fkey'), 'data_sources', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'conflicts_of_interest', type_='foreignkey')
    op.create_foreign_key(op.f('conflicts_of_interest_project_id_fkey'), 'conflicts_of_interest', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'carbon_credit_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('carbon_credit_tokens_project_id_fkey'), 'carbon_credit_tokens', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'calculation_runs', type_='foreignkey')
    op.drop_constraint(None, 'calculation_runs', type_='foreignkey')
    op.create_foreign_key(op.f('calculation_runs_approved_by_fkey'), 'calculation_runs', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(op.f('calculation_runs_project_id_fkey'), 'calculation_runs', 'projects', ['project_id'], ['id'])
    op.drop_column('calculation_runs', 'version_id')
    op.drop_constraint(None, 'brokerage_listings', type_='foreignkey')
    op.create_foreign_key(op.f('brokerage_listings_project_id_fkey'), 'brokerage_listings', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_runs_project_id_fkey'), 'agent_runs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
