"""add project pre audit and lead conversion links

Revision ID: 7302c26e5365
Revises: 97432971a11f
Create Date: 2026-08-12 18:05:58.852000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7302c26e5365'
down_revision: Union[str, None] = '97432971a11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_pre_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('validation_run_id', sa.UUID(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'gaps', 'failed', name='pre_audit_status'), nullable=False),
    sa.Column('gap_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_pre_audits_project_id', 'project_pre_audits', ['project_id'], unique=False)
    op.create_index('ix_project_pre_audits_status', 'project_pre_audits', ['status'], unique=False)
    op.add_column('lead_documents', sa.Column('file_upload_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lead_documents', 'file_uploads', ['file_upload_id'], ['id'])
    op.add_column('leads', sa.Column('converted_project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'leads', 'projects', ['converted_project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'converted_project_id')
    op.drop_constraint(None, 'lead_documents', type_='foreignkey')
    op.drop_column('lead_documents', 'file_upload_id')
    op.drop_index('ix_project_pre_audits_status', table_name='project_pre_audits')
    op.drop_index('ix_project_pre_audits_project_id', table_name='project_pre_audits')
    op.drop_table('project_pre_audits')
    sa.Enum('passed', 'gaps', 'failed', name='pre_audit_status').drop(op.get_bind())
    # ### end Alembic commands ###
