"""add application tables

Revision ID: 77a8219f7670
Revises: 21cf99f9b302
Create Date: 2026-08-28 07:45:23.712962+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.encrypted_types  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '77a8219f7670'
down_revision: Union[str, None] = '21cf99f9b302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_email_hash', sa.String(length=255), nullable=False),
    sa.Column('applicant_email_encrypted', app.core.encrypted_types.EncryptedString(length=255), nullable=True),
    sa.Column('organization_name', sa.String(length=500), nullable=True),
    sa.Column('project_title', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('proposed_methodology', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('intake', 'documents_pending', 'pre_audit', 'gaps', 'ready_for_calculation', 'ready_for_review', 'approved', 'submitted', 'rejected', name='application_status'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('converted_project_id', sa.UUID(), nullable=True),
    sa.Column('validation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['converted_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_applicant_email_hash', 'applications', ['applicant_email_hash'], unique=False)
    op.create_index('ix_applications_converted_project_id', 'applications', ['converted_project_id'], unique=False)
    op.create_index('ix_applications_country', 'applications', ['country'], unique=False)
    op.create_index('ix_applications_sector', 'applications', ['sector'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'email', 'drive', 'dropbox', 'registry', 'api', name='application_document_source'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.Enum('pdd', 'monitoring_report', 'kpt_results', 'sales_receipt', 'survey_form', 'gps_data', 'stove_inventory', 'other', name='application_document_type'), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'fetched', 'scanning', 'processed', 'failed', name='application_document_status'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gap_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_documents_application_id', 'application_documents', ['application_id'], unique=False)
    op.create_index('ix_application_documents_document_type', 'application_documents', ['document_type'], unique=False)
    op.create_index('ix_application_documents_status', 'application_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_documents_status', table_name='application_documents')
    op.drop_index('ix_application_documents_document_type', table_name='application_documents')
    op.drop_index('ix_application_documents_application_id', table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_sector', table_name='applications')
    op.drop_index('ix_applications_country', table_name='applications')
    op.drop_index('ix_applications_converted_project_id', table_name='applications')
    op.drop_index('ix_applications_applicant_email_hash', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
