"""add lead_documents table

Revision ID: 7c34945da69e
Revises: c5bd1ba5368d
Create Date: 2026-08-01 09:32:33.973513+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c34945da69e'
down_revision: Union[str, None] = 'c5bd1ba5368d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'fetched', 'failed', name='lead_document_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_documents_document_type', 'lead_documents', ['document_type'], unique=False)
    op.create_index('ix_lead_documents_lead_id', 'lead_documents', ['lead_id'], unique=False)
    op.create_index('ix_lead_documents_status', 'lead_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lead_documents_status', table_name='lead_documents')
    op.drop_index('ix_lead_documents_lead_id', table_name='lead_documents')
    op.drop_index('ix_lead_documents_document_type', table_name='lead_documents')
    op.drop_table('lead_documents')
    sa.Enum('discovered', 'fetched', 'failed', name='lead_document_status').drop(op.get_bind())
    # ### end Alembic commands ###
