"""add_lead_intelligence_table

Revision ID: 83f9a053933f
Revises: 0003_orchestrator
Create Date: 2026-05-25 12:47:46.969895+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f9a053933f'
down_revision: Union[str, None] = '0003_orchestrator'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_source', sa.Enum('verra', 'gold_standard', 'cdm', 'kenya_national', 'manual', name='lead_registry_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('project_developer', sa.String(length=500), nullable=True),
    sa.Column('developer_contact', sa.String(length=500), nullable=True),
    sa.Column('developer_email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('location_coords', sa.String(length=100), nullable=True),
    sa.Column('methodology', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('under_validation', 'under_verification', 'registered', 'certified', 'rejected', 'completed', 'unknown', name='lead_project_status'), nullable=False),
    sa.Column('crediting_period_start', sa.Date(), nullable=True),
    sa.Column('crediting_period_end', sa.Date(), nullable=True),
    sa.Column('last_verification_date', sa.Date(), nullable=True),
    sa.Column('last_monitoring_period_end', sa.Date(), nullable=True),
    sa.Column('estimated_credits_per_year', sa.Float(), nullable=True),
    sa.Column('registry_url', sa.Text(), nullable=True),
    sa.Column('days_in_status', sa.Integer(), nullable=True),
    sa.Column('stuck_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='lead_priority'), nullable=False),
    sa.Column('lead_status', sa.Enum('new', 'contacted', 'qualified', 'proposal_sent', 'converted', 'dismissed', name='lead_workflow_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_source', 'external_id', name='uq_lead_registry_external')
    )
    op.create_index('ix_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('ix_leads_country', 'leads', ['country'], unique=False)
    op.create_index('ix_leads_external_id', 'leads', ['external_id'], unique=False)
    op.create_index('ix_leads_lead_status', 'leads', ['lead_status'], unique=False)
    op.create_index('ix_leads_priority', 'leads', ['priority'], unique=False)
    op.create_index('ix_leads_registry_source', 'leads', ['registry_source'], unique=False)
    op.create_index('ix_leads_scraped_at', 'leads', ['scraped_at'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_leads_stuck_score', 'leads', ['stuck_score'], unique=False)
    # NOTE: Indexes for brokerage_listings, brokerage_transactions, buyer_profiles,
    # calculation_runs, carbon_credit_tokens, corporate_portfolios, data_sources,
    # file_uploads, portfolio_holdings, projects, refresh_tokens, reports,
    # token_listings, trade_matches, users are created in migration 0004_add_missing_tables
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_stuck_score', table_name='leads')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_scraped_at', table_name='leads')
    op.drop_index('ix_leads_registry_source', table_name='leads')
    op.drop_index('ix_leads_priority', table_name='leads')
    op.drop_index('ix_leads_lead_status', table_name='leads')
    op.drop_index('ix_leads_external_id', table_name='leads')
    op.drop_index('ix_leads_country', table_name='leads')
    op.drop_index('ix_leads_assigned_to', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
