"""add_lead_intelligence_table

Revision ID: 83f9a053933f
Revises: 0003_orchestrator
Create Date: 2026-05-25 12:47:46.969895+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f9a053933f'
down_revision: Union[str, None] = '0003_orchestrator'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_source', sa.Enum('verra', 'gold_standard', 'cdm', 'kenya_national', 'manual', name='lead_registry_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('project_developer', sa.String(length=500), nullable=True),
    sa.Column('developer_contact', sa.String(length=500), nullable=True),
    sa.Column('developer_email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('location_coords', sa.String(length=100), nullable=True),
    sa.Column('methodology', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('under_validation', 'under_verification', 'registered', 'certified', 'rejected', 'completed', 'unknown', name='lead_project_status'), nullable=False),
    sa.Column('crediting_period_start', sa.Date(), nullable=True),
    sa.Column('crediting_period_end', sa.Date(), nullable=True),
    sa.Column('last_verification_date', sa.Date(), nullable=True),
    sa.Column('last_monitoring_period_end', sa.Date(), nullable=True),
    sa.Column('estimated_credits_per_year', sa.Float(), nullable=True),
    sa.Column('registry_url', sa.Text(), nullable=True),
    sa.Column('days_in_status', sa.Integer(), nullable=True),
    sa.Column('stuck_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='lead_priority'), nullable=False),
    sa.Column('lead_status', sa.Enum('new', 'contacted', 'qualified', 'proposal_sent', 'converted', 'dismissed', name='lead_workflow_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_source', 'external_id', name='uq_lead_registry_external')
    )
    op.create_index('ix_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('ix_leads_country', 'leads', ['country'], unique=False)
    op.create_index('ix_leads_external_id', 'leads', ['external_id'], unique=False)
    op.create_index('ix_leads_lead_status', 'leads', ['lead_status'], unique=False)
    op.create_index('ix_leads_priority', 'leads', ['priority'], unique=False)
    op.create_index('ix_leads_registry_source', 'leads', ['registry_source'], unique=False)
    op.create_index('ix_leads_scraped_at', 'leads', ['scraped_at'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_leads_stuck_score', 'leads', ['stuck_score'], unique=False)
    op.create_index('ix_brokerage_listings_project_id', 'brokerage_listings', ['project_id'], unique=False)
    op.create_index('ix_brokerage_listings_seller_id', 'brokerage_listings', ['seller_id'], unique=False)
    op.create_index('ix_brokerage_listings_status', 'brokerage_listings', ['status'], unique=False)
    op.create_index('ix_brokerage_transactions_buyer_id', 'brokerage_transactions', ['buyer_id'], unique=False)
    op.create_index('ix_brokerage_transactions_listing_id', 'brokerage_transactions', ['listing_id'], unique=False)
    op.create_index('ix_brokerage_transactions_seller_id', 'brokerage_transactions', ['seller_id'], unique=False)
    op.create_index('ix_brokerage_transactions_status', 'brokerage_transactions', ['status'], unique=False)
    op.create_index('ix_buyer_profiles_user_id', 'buyer_profiles', ['user_id'], unique=False)
    op.create_index('ix_calculation_runs_project_id', 'calculation_runs', ['project_id'], unique=False)
    op.create_index('ix_calculation_runs_status', 'calculation_runs', ['status'], unique=False)
    op.create_index('ix_carbon_credit_tokens_project_id', 'carbon_credit_tokens', ['project_id'], unique=False)
    op.create_index('ix_carbon_credit_tokens_status', 'carbon_credit_tokens', ['status'], unique=False)
    op.create_index('ix_corporate_portfolios_user_id', 'corporate_portfolios', ['user_id'], unique=False)
    op.create_index('ix_data_sources_project_id', 'data_sources', ['project_id'], unique=False)
    op.create_index('ix_data_sources_source_type', 'data_sources', ['source_type'], unique=False)
    op.create_index('ix_file_uploads_project_id', 'file_uploads', ['project_id'], unique=False)
    op.create_index('ix_file_uploads_status', 'file_uploads', ['status'], unique=False)
    op.create_index('ix_portfolio_holdings_portfolio_id', 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_holdings_token_id', 'portfolio_holdings', ['token_id'], unique=False)
    op.create_index('ix_projects_developer_id', 'projects', ['developer_id'], unique=False)
    op.create_index('ix_projects_methodology', 'projects', ['methodology'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_index('ix_refresh_tokens_issued_at', 'refresh_tokens', ['issued_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_token_listings_status', 'token_listings', ['status'], unique=False)
    op.create_index('ix_token_listings_token_id', 'token_listings', ['token_id'], unique=False)
    op.create_index('ix_trade_matches_buyer_id', 'trade_matches', ['buyer_id'], unique=False)
    op.create_index('ix_trade_matches_listing_id', 'trade_matches', ['listing_id'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_trade_matches_listing_id', table_name='trade_matches')
    op.drop_index('ix_trade_matches_buyer_id', table_name='trade_matches')
    op.drop_index('ix_token_listings_token_id', table_name='token_listings')
    op.drop_index('ix_token_listings_status', table_name='token_listings')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_project_id', table_name='reports')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_issued_at', table_name='refresh_tokens')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_methodology', table_name='projects')
    op.drop_index('ix_projects_developer_id', table_name='projects')
    op.drop_index('ix_portfolio_holdings_token_id', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_portfolio_id', table_name='portfolio_holdings')
    op.drop_index('ix_file_uploads_status', table_name='file_uploads')
    op.drop_index('ix_file_uploads_project_id', table_name='file_uploads')
    op.drop_index('ix_data_sources_source_type', table_name='data_sources')
    op.drop_index('ix_data_sources_project_id', table_name='data_sources')
    op.drop_index('ix_corporate_portfolios_user_id', table_name='corporate_portfolios')
    op.drop_index('ix_carbon_credit_tokens_status', table_name='carbon_credit_tokens')
    op.drop_index('ix_carbon_credit_tokens_project_id', table_name='carbon_credit_tokens')
    op.drop_index('ix_calculation_runs_status', table_name='calculation_runs')
    op.drop_index('ix_calculation_runs_project_id', table_name='calculation_runs')
    op.drop_index('ix_buyer_profiles_user_id', table_name='buyer_profiles')
    op.drop_index('ix_brokerage_transactions_status', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_transactions_seller_id', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_transactions_listing_id', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_transactions_buyer_id', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_listings_status', table_name='brokerage_listings')
    op.drop_index('ix_brokerage_listings_seller_id', table_name='brokerage_listings')
    op.drop_index('ix_brokerage_listings_project_id', table_name='brokerage_listings')
    op.drop_index('ix_leads_stuck_score', table_name='leads')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_scraped_at', table_name='leads')
    op.drop_index('ix_leads_registry_source', table_name='leads')
    op.drop_index('ix_leads_priority', table_name='leads')
    op.drop_index('ix_leads_lead_status', table_name='leads')
    op.drop_index('ix_leads_external_id', table_name='leads')
    op.drop_index('ix_leads_country', table_name='leads')
    op.drop_index('ix_leads_assigned_to', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
