"""add_user_invites_table

Revision ID: 9c8caee4465a
Revises: 51b30e727848
Create Date: 2026-05-29 05:06:59.657882+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c8caee4465a'
down_revision: Union[str, None] = '51b30e727848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'operator', 'developer', 'viewer', name='user_role', create_type=False), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_user_invites_email_hash', 'user_invites', ['email_hash'], unique=False)
    op.create_index('ix_user_invites_expires_at', 'user_invites', ['expires_at'], unique=False)
    op.create_index('ix_user_invites_token', 'user_invites', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_invites_token', table_name='user_invites')
    op.drop_index('ix_user_invites_expires_at', table_name='user_invites')
    op.drop_index('ix_user_invites_email_hash', table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
