"""add_scraper_runs_table

Revision ID: 9fc7bf9a9f48
Revises: dfabefdb1273
Create Date: 2026-05-25 16:30:06.507706+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc7bf9a9f48'
down_revision: Union[str, None] = 'dfabefdb1273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_runs_scraped_at'), 'scraper_runs', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_scraper_runs_source'), 'scraper_runs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_runs_source'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_scraped_at'), table_name='scraper_runs')
    op.drop_table('scraper_runs')
    # ### end Alembic commands ###
