"""add_user_settings_column

Revision ID: c5b7ac42371a
Revises: ab7db18e2c68
Create Date: 2026-05-26 12:02:51.258790+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b7ac42371a'
down_revision: Union[str, None] = 'ab7db18e2c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'human_escalations', 'validation_step_executions', ['step_execution_id'], ['id'])
    op.add_column('users', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default=sa.text("'{}'")))
    op.alter_column('users', 'settings', nullable=False, server_default=None)
    op.create_foreign_key(None, 'validation_remediations', 'validation_step_executions', ['step_execution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_remediations', type_='foreignkey')
    op.drop_column('users', 'settings')
    op.drop_constraint(None, 'human_escalations', type_='foreignkey')
    # ### end Alembic commands ###
