"""add_missing_tables_and_indexes

Revision ID: c8e8775f56b9
Revises: 9fc7bf9a9f48
Create Date: 2026-05-25 21:08:53.107394+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e8775f56b9'
down_revision: Union[str, None] = '9fc7bf9a9f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('data_ingested', 'calculation_run', 'report_generated', 'human_reviewed', 'report_approved', 'vvb_submitted', 'vvb_responded', 'methodology_updated', 'user_login', 'user_logout', 'mfa_enabled', 'mfa_disabled', 'data_exported', 'consent_given', 'consent_revoked', 'dsr_received', 'dsr_fulfilled', 'breach_reported', name='audit_action_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('radix_tx_ref', sa.String(length=256), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.CheckConstraint("actor_type IN ('user', 'agent', 'system')", name='check_actor_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_type', 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('breach_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('detected', 'under_investigation', 'contained', 'notified_regulator', 'notified_subjects', 'resolved', name='breach_status'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_by', sa.UUID(), nullable=True),
    sa.Column('affected_subjects_count', sa.Integer(), nullable=True),
    sa.Column('affected_data_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('containment_measures', sa.Text(), nullable=True),
    sa.Column('regulator_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subjects_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('buyer_type', sa.Enum('corporate', 'retailer', 'offset_seeker', 'wholesaler', name='buyer_type'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_methodologies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('price_range_min_usd', sa.Float(), nullable=True),
    sa.Column('price_range_max_usd', sa.Float(), nullable=True),
    sa.Column('preferred_locations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('delivery_timeline_preference_days', sa.Integer(), nullable=False),
    sa.Column('auto_match_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_buyer_profiles_user_id', 'buyer_profiles', ['user_id'], unique=False)
    op.create_table('corporate_portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_credits_held', sa.Float(), nullable=False),
    sa.Column('total_credits_retired', sa.Float(), nullable=False),
    sa.Column('portfolio_value_usd', sa.Float(), nullable=False),
    sa.Column('esg_report_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_corporate_portfolios_user_id', 'corporate_portfolios', ['user_id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('access', 'rectification', 'erasure', 'restriction', 'portability', 'objection', name='dsr_type'), nullable=False),
    sa.Column('status', sa.Enum('received', 'under_review', 'fulfilled', 'rejected', 'escalated', name='dsr_status'), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('methodology_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('methodology_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('methodology_name', 'version', name='uq_methodology_version')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_issued_at', 'refresh_tokens', ['issued_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('brokerage_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('available_credits', sa.Float(), nullable=False),
    sa.Column('price_per_credit_usd', sa.Float(), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.String(length=100), nullable=False),
    sa.Column('co_benefits', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('delivery_timeline_days', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'sold', 'withdrawn', name='listing_status'), nullable=False),
    sa.Column('minimum_purchase', sa.Float(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brokerage_listings_project_id', 'brokerage_listings', ['project_id'], unique=False)
    op.create_index('ix_brokerage_listings_seller_id', 'brokerage_listings', ['seller_id'], unique=False)
    op.create_index('ix_brokerage_listings_status', 'brokerage_listings', ['status'], unique=False)
    op.create_table('conflicts_of_interest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('disclosed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('consent_type', sa.Enum('data_processing', 'marketing', 'third_party_sharing', 'photo_retention', 'biometric', name='consent_type'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enumerators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', app.core.encrypted_types.EncryptedString(length=50), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('submissions_count', sa.Integer(), nullable=False),
    sa.Column('rejections_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokerage_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('trade_type', sa.Enum('spot', 'forward', 'escrow', name='trade_type'), nullable=False),
    sa.Column('credits_amount', sa.Float(), nullable=False),
    sa.Column('price_per_credit_usd', sa.Float(), nullable=False),
    sa.Column('total_value_usd', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('commission_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'in_escrow', 'completed', 'cancelled', 'disputed', name='transaction_status'), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('escrow_release_date', sa.Date(), nullable=True),
    sa.Column('vvb_certificate_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['brokerage_listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brokerage_transactions_buyer_id', 'brokerage_transactions', ['buyer_id'], unique=False)
    op.create_index('ix_brokerage_transactions_listing_id', 'brokerage_transactions', ['listing_id'], unique=False)
    op.create_index('ix_brokerage_transactions_seller_id', 'brokerage_transactions', ['seller_id'], unique=False)
    op.create_index('ix_brokerage_transactions_status', 'brokerage_transactions', ['status'], unique=False)
    op.create_table('carbon_credit_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('calculation_run_id', sa.UUID(), nullable=False),
    sa.Column('tonnes_co2e', sa.Float(), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.String(length=100), nullable=False),
    sa.Column('vvb_registry', sa.String(length=100), nullable=False),
    sa.Column('vvb_certificate_id', sa.String(length=255), nullable=True),
    sa.Column('radix_token_address', sa.String(length=256), nullable=True),
    sa.Column('radix_resource_address', sa.String(length=256), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('minted', 'listed', 'sold', 'retired', 'fractional', name='token_status'), nullable=False),
    sa.Column('is_fractional', sa.Boolean(), nullable=False),
    sa.Column('parent_token_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carbon_credit_tokens_project_id', 'carbon_credit_tokens', ['project_id'], unique=False)
    op.create_index('ix_carbon_credit_tokens_status', 'carbon_credit_tokens', ['status'], unique=False)
    op.create_table('trade_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('methodology_match', sa.Boolean(), nullable=False),
    sa.Column('price_match', sa.Boolean(), nullable=False),
    sa.Column('location_match', sa.Boolean(), nullable=False),
    sa.Column('timeline_match', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['brokerage_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_matches_buyer_id', 'trade_matches', ['buyer_id'], unique=False)
    op.create_index('ix_trade_matches_listing_id', 'trade_matches', ['listing_id'], unique=False)
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', app.core.encrypted_types.EncryptedString(length=50), nullable=False),
    sa.Column('flow_type', sa.Enum('survey', 'photo_collection', 'support', 'onboarding', 'idle', name='conversation_flow'), nullable=False),
    sa.Column('state', sa.Enum('active', 'completed', 'abandoned', 'waiting_human', name='conversation_state'), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('assigned_enumerator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_enumerator_id'], ['enumerators.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('invoiced', sa.Boolean(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['brokerage_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('buyer_deposited', sa.Boolean(), nullable=False),
    sa.Column('seller_transferred', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['brokerage_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('tonnes_held', sa.Float(), nullable=False),
    sa.Column('tonnes_retired', sa.Float(), nullable=False),
    sa.Column('acquisition_price_usd', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['corporate_portfolios.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['carbon_credit_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_holdings_portfolio_id', 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_holdings_token_id', 'portfolio_holdings', ['token_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', app.core.encrypted_types.EncryptedString(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('enumerator_id', sa.UUID(), nullable=True),
    sa.Column('household_id', app.core.encrypted_types.EncryptedString(length=100), nullable=True),
    sa.Column('stove_id', sa.String(length=100), nullable=True),
    sa.Column('village_name', sa.String(length=255), nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'valid', 'flagged', 'rejected', name='survey_validation_status'), nullable=False),
    sa.Column('validation_errors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('submitted_via', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ),
    sa.ForeignKeyConstraint(['enumerator_id'], ['enumerators.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('price_per_tonne_usd', sa.Float(), nullable=False),
    sa.Column('amount_available', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['carbon_credit_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_listings_status', 'token_listings', ['status'], unique=False)
    op.create_index('ix_token_listings_token_id', 'token_listings', ['token_id'], unique=False)
    op.create_table('token_retirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('retired_by', sa.UUID(), nullable=False),
    sa.Column('tonnes_retired', sa.Float(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_location', sa.String(length=255), nullable=True),
    sa.Column('radix_burn_tx_ref', sa.String(length=256), nullable=True),
    sa.Column('retirement_certificate_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['retired_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['carbon_credit_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.alter_column('calculation_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_calculation_runs_project_id', 'calculation_runs', ['project_id'], unique=False)
    op.create_index('ix_calculation_runs_status', 'calculation_runs', ['status'], unique=False)
    op.alter_column('data_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_data_sources_project_id', 'data_sources', ['project_id'], unique=False)
    op.create_index('ix_data_sources_source_type', 'data_sources', ['source_type'], unique=False)
    op.alter_column('file_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_uploads', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('human_review_queue', 'sla_deadline',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('human_review_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_review_queue', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_human_review_queue_assigned_to', 'human_review_queue', ['assigned_to'], unique=False)
    op.create_index('ix_human_review_queue_status', 'human_review_queue', ['status'], unique=False)
    op.alter_column('orchestrator_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_orchestrator_events_event_type'), table_name='orchestrator_events')
    op.drop_index(op.f('ix_orchestrator_events_project_id'), table_name='orchestrator_events')
    op.add_column('projects', sa.Column('brokerage_enabled', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('tokenization_enabled', sa.Boolean(), nullable=False))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_projects_developer_id', 'projects', ['developer_id'], unique=False)
    op.create_index('ix_projects_methodology', 'projects', ['methodology'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.add_column('users', sa.Column('mfa_secret', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'mfa_secret')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_project_id', table_name='reports')
    op.alter_column('reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_methodology', table_name='projects')
    op.drop_index('ix_projects_developer_id', table_name='projects')
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('projects', 'tokenization_enabled')
    op.drop_column('projects', 'brokerage_enabled')
    op.create_index(op.f('ix_orchestrator_events_project_id'), 'orchestrator_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_orchestrator_events_event_type'), 'orchestrator_events', ['event_type'], unique=False)
    op.alter_column('orchestrator_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_human_review_queue_status', table_name='human_review_queue')
    op.drop_index('ix_human_review_queue_assigned_to', table_name='human_review_queue')
    op.alter_column('human_review_queue', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('human_review_queue', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_review_queue', 'sla_deadline',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('file_uploads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_data_sources_source_type', table_name='data_sources')
    op.drop_index('ix_data_sources_project_id', table_name='data_sources')
    op.alter_column('data_sources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_calculation_runs_status', table_name='calculation_runs')
    op.drop_index('ix_calculation_runs_project_id', table_name='calculation_runs')
    op.alter_column('calculation_runs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'], unique=False)
    op.alter_column('agent_runs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agent_runs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table('token_retirements')
    op.drop_index('ix_token_listings_token_id', table_name='token_listings')
    op.drop_index('ix_token_listings_status', table_name='token_listings')
    op.drop_table('token_listings')
    op.drop_table('survey_responses')
    op.drop_table('support_tickets')
    op.drop_index('ix_portfolio_holdings_token_id', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_portfolio_id', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_table('escrows')
    op.drop_table('commissions')
    op.drop_table('whatsapp_conversations')
    op.drop_index('ix_trade_matches_listing_id', table_name='trade_matches')
    op.drop_index('ix_trade_matches_buyer_id', table_name='trade_matches')
    op.drop_table('trade_matches')
    op.drop_index('ix_carbon_credit_tokens_status', table_name='carbon_credit_tokens')
    op.drop_index('ix_carbon_credit_tokens_project_id', table_name='carbon_credit_tokens')
    op.drop_table('carbon_credit_tokens')
    op.drop_index('ix_brokerage_transactions_status', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_transactions_seller_id', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_transactions_listing_id', table_name='brokerage_transactions')
    op.drop_index('ix_brokerage_transactions_buyer_id', table_name='brokerage_transactions')
    op.drop_table('brokerage_transactions')
    op.drop_table('enumerators')
    op.drop_table('consent_records')
    op.drop_table('conflicts_of_interest')
    op.drop_index('ix_brokerage_listings_status', table_name='brokerage_listings')
    op.drop_index('ix_brokerage_listings_seller_id', table_name='brokerage_listings')
    op.drop_index('ix_brokerage_listings_project_id', table_name='brokerage_listings')
    op.drop_table('brokerage_listings')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_issued_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('methodology_versions')
    op.drop_table('data_subject_requests')
    op.drop_index('ix_corporate_portfolios_user_id', table_name='corporate_portfolios')
    op.drop_table('corporate_portfolios')
    op.drop_index('ix_buyer_profiles_user_id', table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_table('breach_notifications')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_type', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
